### ISSUE TITLE
MemoryError when process "beer" dataset

### ISSUE THREAD

**Issue by techstone** [ruidan/Unsupervised-Aspect-Extraction#1]
When I try the beer dataset, there is a MemoryError occurred, due to a large number of the dataset to be padding.   But it works well on "restaurant" dataset. 
![wx20171227-103123](https://user-images.githubusercontent.com/3388926/34366555-2e73fe3a-eaf1-11e7-9f4c-edcefd324b53.png)

**Comment by ruidan** [comment]
Memory size of the machine I used is 65840088 KiB, so I didn't encounter this problem. But now the data preparing part is generally not well written as it takes a long time (around 20 mins) on large dataset like "beer". 

You can try a few ways to make it work on your machine. For example, randomly sample a subset (e.g. size=50000) before padding.   Or you can pad the sentence inside the batch/negative generator instead of the beginning. In this case, you need to modify the network a little bit to set the sequence length of input to "None" to allow the shape of different batches to be different.

**Comment by techstone** [comment]
Thanks very much for your reply, It works well on a new machine now.
![wx20171227-164335](https://user-images.githubusercontent.com/3388926/34371927-1cf443c0-eb25-11e7-861e-c93acd368d16.png)
